apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all
spec:
  description: "TEMPORARY: allow all ingress and egress for all pods"
  endpointSelector: {}  # Selects all pods
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
