apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-vkm
  labels:
    app.kubernetes.io/component: "cluster-issuer"
    environment: "vkm-production"
    managed-by: "kubecloud"
    organization: "tu-darmstadt"
    department: "vkm"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selfSigned: {}