# Generated cert-manager CRD types
# This file should be generated by nixidy but cert-manager CRDs have multiple documents
# For now, we'll use basic types and the module will handle CRD installation via Helm
{lib}: {
  # Certificate resource type
  certificates = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "Certificate resources";
  };

  # CertificateRequest resource type
  certificateRequests = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "CertificateRequest resources";
  };

  # Issuer resource type
  issuers = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "Issuer resources";
  };

  # ClusterIssuer resource type
  clusterIssuers = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "ClusterIssuer resources";
  };

  # Order resource type (ACME)
  orders = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "Order resources";
  };

  # Challenge resource type (ACME)
  challenges = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = {};
    description = "Challenge resources";
  };
}