{
  nixidy = {
    bootstrapManifest.enable = true;
    target = {
      repository = "https://github.com/dtdttech/kubecloud.git";
      branch = "master";
      rootPath = "./rendered/dev";
    };
    extraFiles."README.md".text = ''
      # Rendered manifests for Development

      The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy)
      for the development deployment.
    '';
  };
  
  networking.domain = "dev.local";

  # Storage configuration for development environment
  storage = {
    defaultProvider = "local";  # Use local storage for development
    providers = {
      local = {
        enable = true;
        storageClass.isDefault = true;  # Set as default storage class
      };
      ceph.enable = false;     # Disable Ceph in development
      longhorn.enable = false; # Disable Longhorn in development
    };
  };

  # Secrets configuration for development environment
  secrets = {
    defaultProvider = "internal";  # Use internal secrets for development
    commonLabels = {
      "environment" = "development";
      "managed-by" = "kubecloud";
    };
    providers = {
      internal = {
        enable = true;
        validation.enable = true;  # Enable validation for development
        monitoring.enable = true;  # Enable monitoring for development
      };
      external.enable = false;  # Disable external secrets in development
    };
  };

  # Development configuration (smaller resources, simpler setup)
  documentation.bookstack = {
    enable = true;
    domain = "bookstack.dev.local";
    timezone = "UTC";
    database = {
      name = "bookstack_dev";
      user = "bookstack_dev";
      password = "dev123";
    };
    storage = {
      provider = "local";      # Use local storage
      database.size = "5Gi";   # Smaller database for development
      config.size = "1Gi";     # Smaller config storage for development
    };
  };

  identity.keycloak = {
    enable = true;
    domain = "keycloak.dev.local";
    mode = "development";      # Development mode for Keycloak
    admin = {
      username = "admin";
      password = "admin";      # Simple password for development
    };
    database = {
      name = "keycloak_dev";
      user = "keycloak_dev";
      password = "dev123";
    };
  };

  security.passbolt = {
    enable = true;
    domain = "passbolt.dev.local";
    database.password = "dev123";
  };
}