{
  nixidy = {
    bootstrapManifest.enable = true;
    target = {
      repository = "https://github.com/dtdttech/kubecloud.git";
      branch = "master";
      rootPath = "./rendered/vkm";
    };
    extraFiles."README.md".text = ''
      # Rendered manifests for VKM

      The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy)
      for the VKM (Fachgebiet für Verbrennungskraftmaschinen und Fahrzeugantriebe) deployment.
    '';
  };
  
  networking.domain = "vkm.maschinenbau.tu-darmstadt.de";

  # Storage configuration for VKM production environment
  storage = {
    defaultProvider = "ceph";  # Use Ceph for production
    storageClasses = {
      rwo = "ceph-rbd";        # ReadWriteOnce uses RBD (block storage)
      rwx = "ceph-cephfs";     # ReadWriteMany uses CephFS (filesystem)
      rox = "ceph-cephfs";     # ReadOnlyMany uses CephFS (filesystem)
    };
    providers = {
      local.enable = false;    # Disable local storage in production
      ceph = {
        enable = true;
        cluster = {
          clusterID = "vkm-ceph-cluster";
          monitors = [
            "10.0.1.10:6789"
            "10.0.1.11:6789"
            "10.0.1.12:6789"
          ];
        };
        secrets = {
          userID = "kubernetes";
          userKey = "AQBQVkNhL1VkBhAAzOWOCpQNbCOg0BlpKQv6Wg==";
          adminID = "admin";
          adminKey = "AQBQVkNhYQJkBhAAb8OVKqP3F6k7zK4OvA2T7w==";
        };
      };
      longhorn.enable = false; # Disable Longhorn (using Ceph instead)
    };
  };

  # VKM-specific configuration
  documentation.bookstack = {
    enable = true;
    domain = "wiki.vkm.maschinenbau.tu-darmstadt.de";
    timezone = "Europe/Berlin";
    database = {
      name = "bookstack_vkm";
      user = "bookstack_vkm";
      password = "bookstack_vkm_secure123";
    };
    storage = {
      provider = "ceph";  # Use Ceph storage for BookStack
      database.size = "50Gi";  # Larger database for production
      config.size = "10Gi";    # Larger config storage for production
    };
  };

  identity.keycloak = {
    enable = true;
    domain = "sso.vkm.maschinenbau.tu-darmstadt.de";
    mode = "production";
    admin = {
      username = "admin";
      password = "keycloak_vkm_admin123";
    };
    database = {
      name = "keycloak_vkm";
      user = "keycloak_vkm";
      password = "keycloak_vkm_secure123";
    };
  };

  scheduling.librebooking = {
    enable = true;
    domain = "booked.vkm.maschinenbau.tu-darmstadt.de";
    timezone = "Europe/Berlin";
    environment = "production";
    database = {
      name = "librebooking_vkm";
      user = "librebooking_vkm";
      password = "librebooking_vkm_secure123";
    };
    install = {
      password = "install_vkm_secure123";
    };
  };

  support.zammad = {
    enable = true;
    domain = "support.vkm.maschinenbau.tu-darmstadt.de";
    version = "6.5.1";
    timezone = "Europe/Berlin";
    database = {
      name = "zammad_vkm";
      user = "zammad_vkm";
      password = "zammad_vkm_secure123";
    };
    elasticsearch = {
      enabled = true;
      version = "8.19.2";
    };
  };

  security.passbolt = {
    enable = true;
    domain = "warden.vkm.maschinenbau.tu-darmstadt.de";
    database = {
      password = "passbolt_vkm_secure123";
    };
  };

  security.acme-dns = {
    enable = true;
    domain = "adns.vkm.maschinenbau.tu-darmstadt.de";
    nsname = "adns.vkm.maschinenbau.tu-darmstadt.de";
    nsadmin = "admin.vkm.maschinenbau.tu-darmstadt.de";
    debug = false;
    logging = {
      level = "info";
      format = "json";
    };
  };
}