name: Build VKM Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-vkm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
    
    - name: Build VKM profile with Nixidy
      uses: arnarg/nixidy/actions/build@main
      id: build
      with:
        environment: .#vkm

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vkm-build
        path: ${{ steps.build.outputs.out-path }}

  deploy-vkm:
    needs: build-vkm
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: vkm-build
        path: build-output

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        path: kubevkm_rendered

    - name: Copy build results
      run: |
        rsync --recursive --delete build-output/ kubevkm_rendered/

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      id: commit
      with:
        default_author: github_actions
        message: "chore: promote to dev ${{github.sha}}"
        fetch: false
        new_branch: promote/env/dev
        push: --force-with-lease origin promote/env/dev

    - name: Create Pull Request
      if: ${{ steps.commit.outputs.pushed == 'true' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        head: promote/env/dev
        base: master
        title: "chore: promote to dev ${{github.sha}}"
        body: |
          Automated deployment from commit ${{github.sha}}
          
          This PR was created automatically by the VKM build workflow.