name: Build VKM Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-vkm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    
    - name: Build VKM profile with Nixidy
      uses: arnarg/nixidy/actions/build@main
      id: build
      with:
        environment: .#vkm

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        path: kubevkm_rendered

    - name: Copy build results
      run: |
        rsync --recursive --delete '${{steps.build.outputs.out-path}}/' kubevkm_rendered/

    - name: Configure Git
      run: |
        cd kubevkm_rendered
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        cd kubevkm_rendered
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update VKM rendered configuration

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: GitHub Action <action@github.com>"
          git push origin master
        fi