name: Build and Deploy Nixidy Manifests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Build vkm manifests
      run: |
        nix build .#vkm
        
    - name: Prepare manifests for upload
      run: |
        mkdir -p manifests
        cp -r result/* manifests/
        
    - name: Upload manifests as artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubernetes-manifests
        path: manifests/
        retention-days: 30

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download manifests artifact
      uses: actions/download-artifact@v4
      with:
        name: kubernetes-manifests
        path: manifests/
        
    - name: Checkout rendered repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: '${{ secrets.RENDERED_REPO_TOKEN }}'
        path: rendered-repo
        
    - name: Copy manifests to rendered repository
      run: |
        # Clean existing content in rendered repo
        cd rendered-repo
        find . -type f -not -path './.git/*' -delete
        find . -type d -empty -delete
        
        # Copy new manifests (dereference symlinks)
        cd ..
        cp -rL manifests/* rendered-repo/
        
    - name: Commit and push to rendered repository
      run: |
        cd rendered-repo
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -m "Update manifests from kubecloud@${{ github.sha }}
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        else
          echo "No changes to commit"
        fi