name: Build VKM Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-vkm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: kubecloud
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build VKM profile
      run: nix build .#vkm

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        path: kubevkm_rendered

    - name: Copy build results
      run: ./scripts/copy-result.sh result kubevkm_rendered

    - name: Configure Git
      run: |
        cd kubevkm_rendered
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        cd kubevkm_rendered
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update VKM rendered configuration

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: GitHub Action <action@github.com>"
          git push origin master
        fi