name: Build VKM Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-vkm:
    runs-on: nixery.dev/shell/git
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Enable Nix Flakes
      run: |
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        sudo nix-channel --update
    
    - name: Build VKM profile with Nixidy
      uses: arnarg/nixidy/actions/build@main
      id: build
      with:
        environment: .#vkm

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vkm-build
        path: ${{ steps.build.outputs.out-path }}

  deploy-vkm:
    needs: build-vkm
    runs-on: nixery.dev/shell/git
    steps:
    - name: Enable Nix Flakes
      run: |
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        sudo nix-channel --update
    
    - name: Install rsync
      run: nix-shell -p rsync --run "echo rsync installed"

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        path: kubevkm_rendered
        ref: master  # Explicitly checkout master branch

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: vkm-build
        path: build-output

    - name: Copy build results
      run: |
        rsync --recursive --delete build-output/ kubevkm_rendered/

    - name: Configure Git
      run: |
        cd kubevkm_rendered
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit changes
      run: |
        cd kubevkm_rendered
        git add .
        git commit -m "chore: promote to dev ${{github.sha}}"
        git push origin HEAD:promote/env/dev --force-with-lease

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        head: promote/env/dev
        base: master
        title: "chore: promote to dev ${{github.sha}}"
        body: |
          Automated deployment from commit ${{github.sha}}
          
          This PR was created automatically by the VKM build workflow.