name: Build VKM Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-vkm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
    
    - name: Build VKM profile with Nixidy
      uses: arnarg/nixidy/actions/build@main
      id: build
      continue-on-error: false
      with:
        environment: .#vkm

    - name: Debug build output
      run: |
        echo "Build output path: ${{ steps.build.outputs.out-path }}"
        echo "Build result: ${{ steps.build.outputs.result }}"
        if [ -n "${{ steps.build.outputs.out-path }}" ] && [ -d "${{ steps.build.outputs.out-path }}" ]; then
          echo "Contents of build output:"
          ls -la "${{ steps.build.outputs.out-path }}" || echo "Cannot list directory"
        else
          echo "Build output path does not exist or is not a directory"
        fi

    - name: Prepare build artifacts
      run: |
        # Check if build succeeded and output path exists
        if [ -z "${{ steps.build.outputs.out-path }}" ] || [ ! -d "${{ steps.build.outputs.out-path }}" ]; then
          echo "ERROR: Build output path does not exist or is empty"
          echo "Creating empty artifacts directory to allow upload to proceed"
          mkdir -p artifacts-empty
          exit 0
        fi
        
        # Create a clean directory for artifacts
        mkdir -p artifacts-clean
        
        # Copy all files except those with colons in names
        cd "${{ steps.build.outputs.out-path }}"
        \cp -r --parents * ../artifacts-clean/ 2>/dev/null || true
        
        # Remove any files that still have colons (from symlinks) - only if directory exists and has files
        if [ -d "../artifacts-clean" ] && [ "$(ls -A ../artifacts-clean 2>/dev/null)" ]; then
          find ../artifacts-clean/ -name "*:*" -delete 2>/dev/null || true
        fi
        
        echo "Cleaned artifacts directory:"
        ls -la ../artifacts-clean/ | head -20 || echo "Directory is empty or doesn't exist"
        
    - name: Upload cleaned artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vkm-build
        path: artifacts-clean/
        if-no-files-found: warn

  deploy-vkm:
    needs: build-vkm
    runs-on: ubuntu-latest
    if: always() && needs.build-vkm.result == 'success' && !cancelled()
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: vkm-build
        path: build-output

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: dtdttech/kubevkm_rendered
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        path: kubevkm_rendered

    - name: Copy build results
      run: |
        rsync --recursive --delete build-output/ kubevkm_rendered/

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      id: commit
      with:
        default_author: github_actions
        message: "chore: promote to dev ${{github.sha}}"
        fetch: false
        new_branch: promote/env/dev
        push: --force-with-lease origin promote/env/dev

    - name: Create Pull Request
      if: ${{ steps.commit.outputs.pushed == 'true' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.RENDERED_REPO_TOKEN }}
        head: promote/env/dev
        base: master
        title: "chore: promote to dev ${{github.sha}}"
        body: |
          Automated deployment from commit ${{github.sha}}
          
          This PR was created automatically by the VKM build workflow.
